// Schemify — Developer data transformation toolkit
// Paste JSON, get TypeScript, Zod, GraphQL, OpenAPI, SQL, C#, and more.

export const VERSION = '0.1.0';

export interface TransformResult {
  label: string;
  code: string;
}

export function jsonToTypescript(json: string): TransformResult {
  return {
    label: 'TypeScript',
    code: `// Generated by Schemify v${VERSION}\n// Input: ${json.length} bytes of JSON`,
  };
}

export function jsonToZod(json: string): TransformResult {
  return {
    label: 'Zod',
    code: `// Generated by Schemify v${VERSION}\nimport { z } from 'zod';`,
  };
}