// Schemify — Developer data transformation toolkit
// Paste JSON, get TypeScript, Zod, GraphQL, OpenAPI, SQL, C#, and more.

import type { TransformResult } from './types';

export const VERSION = '0.1.0';

export type { TransformResult } from './types';
export * from './transformers';

export function jsonToZod(json: string): TransformResult {
  return {
    label: 'Zod',
    code: `// Generated by Schemify v${VERSION}\nimport { z } from 'zod';\n// Input: ${json.length} bytes of JSON`,
  };
}
